# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 677e15d439ae5fbac9983abddc4d05948028310d0acfd550169adf4cf9abb7bb0d0b413aa914be8980d8fe64a651fc29065bc649a2aae724341d297ea3a79d7a

test:
  secret_key_base: 3b8bcf398f0f2ce2cdd99081e246fe772c04dd9c101febe264d8d2805c304fe48a52b7b008b917be0d59de1ca2abe481fcf4722f17635351a199b7233d84551e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
